Fix: Prevent redefinition of imported types in model validation (#871)
accordproject/concerto pull request #902
Opened 2024-09-07 19:42 UTC by yashsaraswat2004

# Closes #871
### Changes
- Added validation logic to check for name conflicts between local declarations and imported types.
- Updated `uniqueNames` set to include imported types and prevent redefinition.

### Flags
- Ensure validation does not impact performance significantly.
- Review the handling of imported namespaces across different modules.

### Screenshots or Video
N/A

### Related Issues
- Issue #871

### Author Checklist
- [x] Ensure you provide a [DCO sign-off](https://github.com/probot/dco#how-it-works) for your commits using the `--signoff` option of git commit.
- [x] Vital features and changes captured in unit and/or integration tests.
- [x] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format).
- [x] Extend the documentation, if necessary.
- [x] Merging to `main` from `fork:Yash_fixing-bugs`.

2024-09-07 20:03 UTC, sandyyash15 approved these changes

2024-09-24 10:04 UTC, dselman commented
You've reformatted the files making it very hard to review your changes. Can you please resubmit without reformatting?

2024-09-25 07:28 UTC, yashsaraswat2004 commented
I'm really sorry to change  the formatting of code. I will sure  resubmit it without reformatting.

2024-10-01 15:02 UTC, dselman requested changes
Impossible to review due to amount of whitespace changes.

2024-10-25 16:43 UTC, closed without merging